"""deleting qna blob

Revision ID: 0e909e0a8920
Revises: 2d18b3f547a0
Create Date: 2022-10-25 03:23:49.713944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e909e0a8920'
down_revision = '2d18b3f547a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'qna')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('qna', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
