"""removing answer type

Revision ID: 3d419b25e27b
Revises: a37a30ab454b
Create Date: 2022-11-08 03:41:34.159545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d419b25e27b'
down_revision = 'a37a30ab454b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer_type', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
