"""added binary image field

Revision ID: 4332d5c7f85e
Revises: 869d3a3169e0
Create Date: 2022-11-06 21:18:57.710217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4332d5c7f85e'
down_revision = '869d3a3169e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_string', sa.String(), nullable=True))
    op.drop_column('question', 'qna')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('qna', sa.BLOB(), nullable=True))
    op.drop_column('question', 'question_string')
    # ### end Alembic commands ###
