"""added link field

Revision ID: 48ccada754fb
Revises: b56baf76a290
Create Date: 2022-11-07 09:21:12.037330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ccada754fb'
down_revision = 'b56baf76a290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer_type', sa.String(), nullable=True))
    op.add_column('question', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'link')
    op.drop_column('question', 'answer_type')
    # ### end Alembic commands ###
