"""create_models_table

Revision ID: 4f6332a3db30
Revises: a6e64ca9dedd
Create Date: 2022-10-20 08:52:40.337192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6332a3db30'
down_revision = 'a6e64ca9dedd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('wp_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('wp_id')
                    )
    op.create_table('keyword',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('wp_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('is_processed', sa.Boolean(), nullable=True),
                    sa.Column('is_posted', sa.Boolean(), nullable=True),
                    sa.Column('category_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['category.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('wp_id')
                    )
    op.create_table('question',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question', sa.String(), nullable=True),
                    sa.Column('answer', sa.String(), nullable=True),
                    sa.Column('keyword_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('keyword')
    op.drop_table('category')
    # ### end Alembic commands ###
