"""adding qna blob

Revision ID: 78aeeb1e7a68
Revises: 0e909e0a8920
Create Date: 2022-10-25 03:25:01.524479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78aeeb1e7a68'
down_revision = '0e909e0a8920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('qna', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'qna')
    # ### end Alembic commands ###
