"""adding post id to keyword table

Revision ID: 82029217cdba
Revises: 78aeeb1e7a68
Create Date: 2022-10-27 04:00:55.280975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82029217cdba'
down_revision = '78aeeb1e7a68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('post_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'post_id')
    # ### end Alembic commands ###
