"""added excerpt

Revision ID: 821cef2596de
Revises: 3d419b25e27b
Create Date: 2022-11-08 12:28:22.698182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821cef2596de'
down_revision = '3d419b25e27b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('excerpt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'excerpt')
    # ### end Alembic commands ###
