"""added link field

Revision ID: a37a30ab454b
Revises: 48ccada754fb
Create Date: 2022-11-07 09:24:28.711851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37a30ab454b'
down_revision = '48ccada754fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
