"""adding image url

Revision ID: bd4c2c22dd19
Revises: 4332d5c7f85e
Create Date: 2022-11-06 21:38:06.986888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4c2c22dd19'
down_revision = '4332d5c7f85e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('question', sa.Column('image_wp_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'image_wp_id')
    op.drop_column('question', 'image_url')
    # ### end Alembic commands ###
