"""'create_db'

Revision ID: cd88eb5c2fa5
Revises: 4f6332a3db30
Create Date: 2022-10-20 09:14:59.441154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd88eb5c2fa5'
down_revision = '4f6332a3db30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
